### PR TITLE
Improved queue

### PR DESCRIPTION
**Pull request by ErikBjare**
Haven't done any testing to speak of, but I think this is an improvement.

Should improve reliability overall, thread should also cleanly exit on program close using `atexit` (which we should probably use in other places as well instead of handling signals).

### CODE REVIEW

**Comment by ErikBjare** [comment]
This has passed integration tests in https://github.com/ActivityWatch/activitywatch/pull/82

**Comment by johan-bjareholt** [comment]
test/test_failqueue.py does not seem to work anymore?

**Comment by ErikBjare** [comment]
@johan-bjareholt It works for me now, please test it yourself.

**Comment by johan-bjareholt** [comment]
So we cannot queue insert_event anymore? That could potentially mess up aw-watcher-afk in set_state if aw-server is not accessible.

**Comment by ErikBjare** [comment]
@johan-bjareholt But wasn't aw-watcher-afk rewritten to use heartbeats? That should have removed the need for using `insert_event`, no?

**Comment by johan-bjareholt** [comment]
[Send event is still required!](https://github.com/ActivityWatch/aw-watcher-afk/blob/master/aw_watcher_afk/afk.py#L56) Heartbeats are only for updating the inserted events, and i use insert_event every time we change state to be able to track the hibernation state (since you obviously cannot do heartbeats when the computer is hibernating).

**Comment by johan-bjareholt** [comment]
Pushed a fix in aw-watcher-afk straight to master so insert_event is no longer required.

https://github.com/ActivityWatch/aw-watcher-afk/commit/ebaa72effbddab24b4a17b036a0407b314649b7e

Should we merge this now? Seems to work fine

**Comment by ErikBjare** [comment]
Great, merging.

**Pull request merged**
