### PR TITLE
Added CLI script

### PR DESCRIPTION
**Pull request by ErikBjare**
Very wip

Desired features:

 - [x] List buckets
 - [ ] View info about buckets
 - [ ] List events
 - [ ] Send heartbeat (with or without queueing)
 - [x] Query

### CODE REVIEW

**Comment by johan-bjareholt** [comment]
I did the same change as you regarding optional return type in https://github.com/ActivityWatch/aw-client/pull/33/commits/b4187e76fdb907d7abc053a4bc6a0bb7d8c19596

**Comment by johan-bjareholt** [comment]
I have also fixed the self.testing in the mockclient which fails in this PR on my PR: https://github.com/ActivityWatch/aw-client/pull/33

**Comment by ErikBjare** [comment]
Pretty neat 
image

**Comment by ErikBjare** [comment]
Just going to go ahead and merge this even though it's a WIP (doesn't affect old functionality)

**Pull request merged**
